---
name: "Build test freenginx"

on:
  push:
    paths:
      - "freenginx/**"
      - "!freenginx/**/*.md"
  pull_request:
    paths:
      - "freenginx/**"
      - "!freenginx/**/*.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  WORK_DIR: freenginx

jobs:
  build:
    name: "Build test image"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, platform: linux/amd64 }
          - { os: ubuntu-24.04-arm, platform: linux/arm64 }
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Resolve upstream versions"
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          echo "NGX_VERSION=$(gh api --paginate repos/freenginx/nginx/tags \
            --jq '.[] | select(.name | test("^release-[0-9]+\\.[0-9]+\\.[0-9]+$")) | .name | sub("^release-"; "")' | sort -V | tail -n 1)" >> "$GITHUB_ENV"
          . scripts/ci-deps.sh

      - name: "Build freenginx"
        working-directory: ${{ env.WORK_DIR }}
        shell: bash
        run: |
          dpkg --print-architecture 2>/dev/null || uname -m

          set -euxo pipefail
          curl -fsSL -O https://github.com/nginx/pkg-oss/raw/master/alpine/alpine/nginx.conf
          curl -fsSL -O https://github.com/nginx/pkg-oss/raw/master/alpine/alpine/nginx.default.conf
          curl -fsSL -O https://github.com/nginx/docker-nginx/raw/master/entrypoint/docker-entrypoint.sh
          curl -fsSL -O https://github.com/nginx/docker-nginx/raw/master/entrypoint/10-listen-on-ipv6-by-default.sh
          curl -fsSL -O https://github.com/nginx/docker-nginx/raw/master/entrypoint/15-local-resolvers.envsh
          curl -fsSL -O https://github.com/nginx/docker-nginx/raw/master/entrypoint/20-envsubst-on-templates.sh
          curl -fsSL -O https://github.com/nginx/docker-nginx/raw/master/entrypoint/30-tune-worker-processes.sh

          docker build \
            --no-cache \
            --progress=plain \
            --platform ${{ matrix.platform }} \
            --build-arg NGX_VERSION=${{ env.NGX_VERSION }} \
            --build-arg HEADERS_MORE_VERSION=${{ env.HEADERS_MORE_VERSION }} \
            --build-arg NGX_ZSTD_VERSION=${{ env.NGX_ZSTD_VERSION }} \
            --build-arg NGX_STRIP_BINARIES=1 \
            --tag $GITHUB_REPOSITORY_OWNER/freenginx:${{ env.NGX_VERSION }}-$(dpkg --print-architecture) \
            . 2>&1 | tee build.log

          docker run --rm \
            --entrypoint freenginx \
            $GITHUB_REPOSITORY_OWNER/freenginx:${{ env.NGX_VERSION }}-$(dpkg --print-architecture) \
            -V
